export interface Career {
  id: string;
  name: string;
  shortName: string;
}

export const careers: Career[] = [
  { id: 'AMC', name: 'Ambiente Construido/Exploración', shortName: 'AMC' },
  { id: 'ARQ', name: 'Arquitectura', shortName: 'ARQ' },
  { id: 'BFI', name: 'B.A. in Finance', shortName: 'BFI' },
  { id: 'BGB', name: 'B.A. in Global Business', shortName: 'BGB' },
  { id: 'BIE', name: 'B.S. Industrial Engineering with minor in Systems Engineering', shortName: 'BIE' },
  { id: 'BME', name: 'B.S. Mechatronics Engineering', shortName: 'BME' },
  { id: 'CIS', name: 'Derecho, Economía y Relaciones Internacionales/Exploración', shortName: 'CIS' },
  { id: 'CPF', name: 'Licenciatura en Contaduría Pública y Finanzas', shortName: 'CPF' },
  { id: 'ESC', name: 'Estudios Creativos/Exploración', shortName: 'ESC' },
  { id: 'IAL', name: 'Ingeniería en Alimentos', shortName: 'IAL' },
  { id: 'IBQ', name: 'Bioingeniería y Procesos Químicos/Exploración', shortName: 'IBQ' },
  { id: 'IBT', name: 'Ingeniería en Biotecnología', shortName: 'IBT' },
  { id: 'IC', name: 'Ingeniería Civil', shortName: 'IC' },
  { id: 'ICI', name: 'Ciencias Aplicadas/Exploración', shortName: 'ICI' },
  { id: 'ICT', name: 'Computación y Tecnologías de Información/Exploración', shortName: 'ICT' },
  { id: 'IDM', name: 'Ingeniería en Ciencia de Datos y Matemáticas', shortName: 'IDM' },
  { id: 'IDS', name: 'Ingeniería en Desarrollo Sustentable', shortName: 'IDS' },
  { id: 'IE', name: 'Ingeniería en Electrónica', shortName: 'IE' },
  { id: 'IFI', name: 'Ingeniería Física Industrial', shortName: 'IFI' },
  { id: 'IID', name: 'Ingeniería en Innovación y Desarrollo', shortName: 'IID' },
  { id: 'IIS', name: 'Ingeniería Industrial y de Sistemas', shortName: 'IIS' },
  { id: 'IIT', name: 'Ingeniería en Innovación y Transformación/Exploración', shortName: 'IIT' },
  { id: 'IM', name: 'Ingeniería Mecánica', shortName: 'IM' },
  { id: 'IMD', name: 'Ingeniería Biomédica', shortName: 'IMD' },
  { id: 'IMT', name: 'Ingeniería en Mecatrónica', shortName: 'IMT' },
  { id: 'INA', name: 'Ingeniería en Nanotecnología', shortName: 'INA' },
  { id: 'IQ', name: 'Ingeniería Química', shortName: 'IQ' },
  { id: 'IRS', name: 'Ingeniería en Robótica y Sistemas Digitales', shortName: 'IRS' },
  { id: 'ITC', name: 'Ingeniería en Tecnologías Computacionales', shortName: 'ITC' },
  { id: 'ITD', name: 'Ingeniería en Transformación Digital de Negocios', shortName: 'ITD' },
  { id: 'LAD', name: 'Licenciatura en Arte Digital', shortName: 'LAD' },
  { id: 'LAE', name: 'Licenciatura en Estrategia y Transformación de Negocios', shortName: 'LAE' },
  { id: 'LAF', name: 'Licenciatura en Finanzas', shortName: 'LAF' },
  { id: 'LBC', name: 'Licenciatura en Biociencias', shortName: 'LBC' },
  { id: 'LC', name: 'Licenciatura en Comunicación', shortName: 'LC' },
  { id: 'LDE', name: 'Licenciatura en Emprendimiento', shortName: 'LDE' },
  { id: 'LDI', name: 'Licenciatura en Diseño', shortName: 'LDI' },
  { id: 'LDO', name: 'Licenciatura en Desarrollo de Talento y Cultura Organizacional', shortName: 'LDO' },
  { id: 'LEC', name: 'Licenciatura en Economía', shortName: 'LEC' },
  { id: 'LED', name: 'Licenciatura en Derecho', shortName: 'LED' },
  { id: 'LEI', name: 'Licenciatura en Innovación Educativa', shortName: 'LEI' },
  { id: 'LEM', name: 'Licenciatura en Mercadotecnia', shortName: 'LEM' },
  { id: 'LIN', name: 'Licenciatura en Negocios Internacionales', shortName: 'LIN' },
  { id: 'LIT', name: 'Licenciatura en Inteligencia de Negocios', shortName: 'LIT' },
  { id: 'LLE', name: 'Licenciatura en Letras Hispánicas', shortName: 'LLE' },
  { id: 'LNBS', name: 'Licenciatura en Nutrición y Bienestar Integral', shortName: 'LNBS' },
  { id: 'LPE', name: 'Licenciatura en Periodismo', shortName: 'LPE' },
  { id: 'LPSS', name: 'Licenciatura en Psicología Clínica y de la Salud', shortName: 'LPSS' },
  { id: 'LRI', name: 'Licenciatura en Relaciones Internacionales', shortName: 'LRI' },
  { id: 'LTM', name: 'Licenciatura en Tecnología y Producción Musical', shortName: 'LTM' },
  { id: 'LTP', name: 'Licenciatura en Gobierno y Transformación Pública', shortName: 'LTP' },
  { id: 'LUB', name: 'Licenciatura en Urbanismo', shortName: 'LUB' },
  { id: 'MCS', name: 'Médico Cirujano', shortName: 'MCS' },
  { id: 'MOS', name: 'Médico Cirujano Odontólogo', shortName: 'MOS' },
  { id: 'NEG', name: 'Negocios/Exploración', shortName: 'NEG' },
  { id: 'SLD', name: 'Salud/Exploración', shortName: 'SLD' }
];

// Exportar como CAREER_OPTIONS para compatibilidad
export const CAREER_OPTIONS = careers;
